site_name: "konglomerat project docs"
site_url: https://projectdocs.konglomerat.org

theme:
  name: 'material'
  custom_dir: 'theme'

plugins:
  - search


repo_url: https://github.com/konglomerat/projectdocs
repo_name: "github:konglomerat/projectdocs"
edit_uri: "edit/master/docs/"