site_name: "Konglomerat project documentation"
site_url: https://konglomerat.github.io/projectdocs/

theme:
  name: 'material'

nav:
  - "index.md"
  - "Rollcontainer":
    - "projects/printercontainer/printercontainer.md"
  - "VeloZack":
    - "projects/velozack/velozack.md"
  - "DIT Laser":
    - "projects/DITLaser/ditlaser.md"

plugins:
  - search

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - attr_list
  - codehilite:
      linenums: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.extra
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - footnotes
  - pymdownx.keys
  - pymdownx.arithmatex

repo_url: https://github.com/konglomerat/projectdocs
repo_name: "gitlab:konglomerat/projectdocs"
edit_uri: "edit/master/docs/"