site_name: "konglomerat project docs"
site_url: https://projectdocs.konglomerat.org

theme:
  name: 'material'
  custom_dir: 'theme'

markdown_extensions:
  - codehilite:
      linenums: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.extra
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - footnotes
  - pymdownx.keys
  - pymdownx.arithmatex

repo_url: https://github.com/konglomerat/projectdocs
repo_name: "github:konglomerat/projectdocs"
edit_uri: "edit/master/docs/"